export const STATUSES = {
  a_traiter: "À traiter",
  garde: "Gardé",
  client_averti: "Client averti",
  rendu: "Rendu",
  envoye: "Envoyé",
  detruit: "Détruit / donné",
};
export const CLOSED_STATUSES = ["rendu", "envoye", "detruit"];
export const CATEGORIES = [
  "Vêtement",
  "Électronique",
  "Bijou / montre",
  "Documents / cartes",
  "Lunettes",
  "Chargeur / câble",
  "Clés",
  "Sac / bagage",
  "Produit de toilette",
  "Autre",
];
export const CHOICE_LABELS = { pickup: "Vient le récupérer", ship: "Demande l'envoi", discard: "Détruire / donner" };

export const isEmail = (v) => typeof v === "string" && /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v.trim());

// Champs d'un objet renvoyés à l'écran de l'hôtel (jamais le jeton invité).
export const ITEM_COLUMNS =
  "id, number, found_at, room_text, room_confirmed, description, category, photo_url, storage_location, status, guest_name, guest_email, notified_at, guest_choice, guest_choice_at, guest_address, guest_phone, notes, created_via, created_at, closed_at";

export const guestText = {
  fr: {
    title: "Un objet a été retrouvé",
    intro: (hotel) => `${hotel} a retrouvé un objet qui pourrait vous appartenir.`,
    foundOn: (d) => `Retrouvé le ${d}`,
    question: "Que souhaitez-vous faire ?",
    pickup: "Je viens le récupérer",
    pickupHelp: "Présentez-vous à la réception de l'hôtel.",
    ship: "Envoyez-le moi",
    shipHelp: "Indiquez votre adresse : l'hôtel vous précisera les frais d'envoi.",
    discard: "Détruisez-le ou donnez-le",
    discardHelp: "Il ne m'appartient pas ou je n'en ai plus besoin.",
    name: "Nom",
    address: "Adresse complète (avec le pays)",
    phone: "Téléphone (facultatif)",
    send: "Envoyer ma demande",
    confirmDiscard: "Confirmer",
    cancel: "Retour",
    thanks: "Merci, votre choix est enregistré.",
    chosen: { pickup: "Vous venez le récupérer à la réception.", ship: "Vous avez demandé l'envoi. L'hôtel vous contactera pour les frais.", discard: "Vous avez demandé que l'objet soit détruit ou donné." },
    change: "Changer mon choix",
    closed: "Cet objet a déjà été traité par l'hôtel. Pour toute question, contactez l'hôtel.",
    error: "Une erreur est survenue. Réessayez dans un instant.",
  },
  en: {
    title: "An item has been found",
    intro: (hotel) => `${hotel} found an item that may belong to you.`,
    foundOn: (d) => `Found on ${d}`,
    question: "What would you like to do?",
    pickup: "I'll come and collect it",
    pickupHelp: "Please ask at the hotel's reception desk.",
    ship: "Please send it to me",
    shipHelp: "Enter your address: the hotel will tell you the shipping cost.",
    discard: "Dispose of it or donate it",
    discardHelp: "It isn't mine, or I no longer need it.",
    name: "Name",
    address: "Full address (including country)",
    phone: "Phone (optional)",
    send: "Send my request",
    confirmDiscard: "Confirm",
    cancel: "Back",
    thanks: "Thank you, your choice has been recorded.",
    chosen: { pickup: "You will collect it at the reception desk.", ship: "You asked for it to be shipped. The hotel will contact you about the cost.", discard: "You asked for the item to be disposed of or donated." },
    change: "Change my choice",
    closed: "This item has already been handled by the hotel. For any question, please contact the hotel.",
    error: "Something went wrong. Please try again in a moment.",
  },
  es: {
    title: "Se ha encontrado un objeto",
    intro: (hotel) => `${hotel} ha encontrado un objeto que podría ser suyo.`,
    foundOn: (d) => `Encontrado el ${d}`,
    question: "¿Qué desea hacer?",
    pickup: "Voy a recogerlo",
    pickupHelp: "Pregunte en la recepción del hotel.",
    ship: "Envíenmelo",
    shipHelp: "Indique su dirección: el hotel le informará del coste del envío.",
    discard: "Destrúyanlo o dónenlo",
    discardHelp: "No es mío o ya no lo necesito.",
    name: "Nombre",
    address: "Dirección completa (con el país)",
    phone: "Teléfono (opcional)",
    send: "Enviar mi solicitud",
    confirmDiscard: "Confirmar",
    cancel: "Volver",
    thanks: "Gracias, su elección ha quedado registrada.",
    chosen: { pickup: "Lo recogerá en la recepción.", ship: "Ha pedido el envío. El hotel le contactará para el coste.", discard: "Ha pedido que el objeto se destruya o se done." },
    change: "Cambiar mi elección",
    closed: "El hotel ya ha gestionado este objeto. Para cualquier duda, contacte con el hotel.",
    error: "Ha ocurrido un error. Inténtelo de nuevo en un momento.",
  },
};
